"""
src/agents/documentation_generator_agent.py

DocumentationGeneratorAgent
============================
Orchestrates the full academic-style project documentation pipeline.

Each of the 18 report sections is generated by a *separate* LLM call so
that the model can focus deeply on each section without context dilution.

The agent runs six preparatory sub-agents first (code analysis, architecture,
API docs, examples) and then fires 18 sequential section-generation calls
to produce a complete project report that mirrors a standard academic format:

    1  Abstract
    2  Introduction
    3  Objectives
    4  Overview of the System
    5  System Analysis
        5.1 Existing System
        5.2 Proposed System
    6  Literature Survey
    8  System Requirements
        8.1 Hardware Requirements
        8.2 Software Requirements
    9  System Implementation
        9.1 Technology Description
        9.2 Module Description
    10 SDLC Methodology
    11 System Design
    12 Coding
    13 Testing
    14 Output Screens
    15 Conclusion
    16 References
"""

from __future__ import annotations

import asyncio
import json
import time
from typing import Any, Dict

from src.agents.base_agent import BaseAgent
from src.agents.code_analyzer_agent import CodeAnalyzerAgent
from src.agents.architecture_detective_agent import ArchitectureDetectiveAgent
from src.agents.api_documenter_agent import APIDocumenterAgent
from src.core.state import DocState


class DocumentationGeneratorAgent(BaseAgent):
    """Generate a full academic-style project report via multiple LLM calls."""

    def __init__(self, llm: Any) -> None:
        super().__init__(llm, "documentation_generator")

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    async def invoke(self, state: DocState) -> Dict[str, Any]:
        t_start = time.monotonic()
        self._trace("starting pipeline")

        # ------------------------------------------------------------------ #
        # Phase 1 — Collect code intelligence (3 existing specialist agents)  #
        # ------------------------------------------------------------------ #
        code_agent = CodeAnalyzerAgent(llm=self.llm)
        self._trace("calling CodeAnalyzerAgent")
        await code_agent.invoke(state)
        self._trace("CodeAnalyzerAgent finished")

        arch_agent = ArchitectureDetectiveAgent(llm=self.llm)
        self._trace("calling ArchitectureDetectiveAgent")
        await arch_agent.invoke(state)
        self._trace("ArchitectureDetectiveAgent finished")

        api_agent = APIDocumenterAgent(llm=self.llm)
        self._trace("calling APIDocumenterAgent")
        await api_agent.invoke(state)
        self._trace("APIDocumenterAgent finished")

        # ------------------------------------------------------------------ #
        # Phase 2 — Build a shared context summary once (reused in prompts)   #
        # ------------------------------------------------------------------ #
        self._trace("building shared context summary")
        ctx = self._build_context_summary(state)
        self._trace("shared context summary ready")

        # ------------------------------------------------------------------ #
        # Phase 3 — Generate each section with its own focused LLM call       #
        # ------------------------------------------------------------------ #
        _delay = 2   # seconds between calls — prevents rate-limit bursts

        self._trace("generating Abstract")
        state["doc_abstract"] = await self._generate_abstract(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Introduction")
        state["doc_introduction"] = await self._generate_introduction(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Objectives")
        state["doc_objectives"] = await self._generate_objectives(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating System Overview")
        state["doc_system_overview"] = await self._generate_system_overview(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Existing System")
        state["doc_existing_system"] = await self._generate_existing_system(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Proposed System")
        state["doc_proposed_system"] = await self._generate_proposed_system(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Literature Survey")
        state["doc_literature_survey"] = await self._generate_literature_survey(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Hardware Requirements")
        state["doc_hardware_requirements"] = await self._generate_hardware_requirements(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Software Requirements")
        state["doc_software_requirements"] = await self._generate_software_requirements(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Technology Description")
        state["doc_technology_description"] = await self._generate_technology_description(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Module Description")
        state["doc_module_description"] = await self._generate_module_description(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating SDLC Methodology")
        state["doc_sdlc_methodology"] = await self._generate_sdlc_methodology(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating System Design")
        state["doc_system_design"] = await self._generate_system_design(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Coding")
        state["doc_coding"] = await self._generate_coding(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Testing")
        state["doc_testing"] = await self._generate_testing(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Output Screens")
        state["doc_output_screens"] = await self._generate_output_screens(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating Conclusion")
        state["doc_conclusion"] = await self._generate_conclusion(ctx)
        await asyncio.sleep(_delay)
        self._trace("generating References")
        state["doc_references"] = await self._generate_references(ctx)

        elapsed = time.monotonic() - t_start
        self._trace("pipeline finished")

        return self.format_output(
            content="Documentation generated successfully.",
            metadata={
                "repo_path": state.get("repo_path", ""),
                "sections_generated": 18,
                "total_duration_seconds": round(elapsed, 3),
            },
        )

    # ------------------------------------------------------------------
    # Context builder — distils the three agent outputs into a compact
    # JSON payload that every section prompt will embed.
    # ------------------------------------------------------------------

    @staticmethod
    def _build_context_summary(state: DocState) -> Dict[str, Any]:
        structure: Dict[str, Any] = state.get("code_structure", {})
        github_url: str = state.get("github_url", "")

        # Derive project name from URL as a guaranteed-non-empty fallback.
        project_name = github_url.rstrip("/").split("/")[-1].replace("-", " ").replace("_", " ") if github_url else "Unknown Project"

        analysis_content: str = (
            state.get("analysis_output", {}).get("content", "") or ""
        )
        architecture_content: str = (
            state.get("architecture_output", {}).get("content", "") or ""
        )
        api_content: str = (
            state.get("api_documentation_output", {}).get("content", "") or ""
        )

        def _truncate(text: str, chars: int = 1500) -> str:
            return text[:chars] + "..." if len(text) > chars else text

        modules: list = structure.get("modules", [])[:40]
        classes: list = structure.get("classes", [])[:25]
        functions: list = structure.get("functions", [])[:30]
        imports: list = structure.get("imports", [])[:40]

        # Infer language/stack from file extensions and import names.
        extensions = list({m.rsplit(".", 1)[-1] for m in modules if "." in m})
        tech_hints = ", ".join(sorted(set(extensions + imports[:10])))

        # Build a minimum viable description even when code structure is sparse.
        if len(analysis_content.strip()) < 100:
            analysis_content = (
                f"Project '{project_name}' from {github_url}. "
                f"Files found: {', '.join(modules[:15]) or 'N/A'}. "
                f"Technology stack hints: {tech_hints or 'N/A'}."
            )
        if len(architecture_content.strip()) < 100:
            architecture_content = (
                f"Repository '{project_name}' contains {len(modules)} source files. "
                f"File extensions detected: {', '.join(extensions) or 'N/A'}. "
                f"Top-level structure: {', '.join(modules[:10]) or 'N/A'}."
            )

        return {
            "github_url": github_url,
            "project_name": project_name,
            "repo_path": state.get("repo_path", ""),
            "modules": modules,
            "classes": [
                {"name": c["name"], "file": c["file"], "methods": c.get("methods", [])[:6]}
                for c in classes
            ],
            "functions": [
                {"name": f["name"], "file": f["file"]}
                for f in functions
            ],
            "imports": imports,
            "tech_hints": tech_hints,
            "analysis_summary": _truncate(analysis_content),
            "architecture_summary": _truncate(architecture_content),
            "api_summary": _truncate(api_content),
            "api_metadata": state.get("api_documentation_output", {}).get("metadata", {}),
        }

    # ------------------------------------------------------------------
    # Section generators — each makes exactly ONE LLM call
    # ------------------------------------------------------------------

    def _trace(self, message: str) -> None:
        print(f"[documentation_generator] {message}", flush=True)

    async def _call_llm(self, prompt: str, fallback: str = "") -> str:
        """Call LLM with retry + back-off to handle rate limits gracefully."""
        last_exc: Exception | None = None
        for attempt in range(3):
            try:
                if attempt > 0:
                    await asyncio.sleep(8 * attempt)   # 8s, 16s
                response = await self.llm.ainvoke(prompt)
                content = response.content if hasattr(response, "content") else str(response)
                if isinstance(content, list):
                    content = "\n".join(str(part) for part in content)
                content = str(content).strip()
                if len(content) >= 5:
                    return content
            except Exception as exc:
                last_exc = exc
                await asyncio.sleep(10 * (attempt + 1))
        return fallback if fallback else (
            f"Content could not be generated. {last_exc}" if last_exc else "Content not available."
        )

    async def _generate_abstract(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the ABSTRACT section of a formal academic project report.

Project Name: {ctx['project_name']}
GitHub URL: {ctx['github_url']}
Technology stack: {ctx['tech_hints']}
Source files: {', '.join(ctx['modules'][:15])}
Code Analysis Summary:
{ctx['analysis_summary']}

Write a concise Abstract (150-250 words) that:
- States the purpose and scope of the software project
- Describes the problem it solves
- Mentions key technologies used
- Summarises the methodology and key outcomes
- Uses formal academic English

Output plain text only (no markdown headings, no bullet lists)."""
        return await self._call_llm(prompt, "Abstract not available.")

    async def _generate_introduction(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the INTRODUCTION section of a formal academic project report.

Project details:
{json.dumps({"project_name": ctx["project_name"], "github_url": ctx["github_url"], "tech_hints": ctx["tech_hints"], "modules": ctx["modules"][:20], "analysis_summary": ctx["analysis_summary"]}, indent=2)}

Write a detailed Introduction (400-600 words) covering:
1. Background and context of the problem domain
2. Motivation for building this system
3. Scope and limitations of the project
4. Brief description of the proposed solution
5. Organisation of the rest of the report

Use formal academic English. Output plain text paragraphs (no markdown headings)."""
        return await self._call_llm(prompt, "Introduction not available.")

    async def _generate_objectives(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the OBJECTIVES section of a formal academic project report.

Project overview:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "analysis_summary": ctx["analysis_summary"], "modules": ctx["modules"][:15]}, indent=2)}

List 6-10 clear, specific, measurable project objectives.
Format each objective as a numbered item starting with an action verb (e.g. "To design…", "To implement…", "To evaluate…").
Output plain numbered list only (no markdown, no extra commentary)."""
        return await self._call_llm(prompt, "Objectives not available.")

    async def _generate_system_overview(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the OVERVIEW OF THE SYSTEM section of a formal academic project report.

Architecture and code details:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "architecture_summary": ctx["architecture_summary"], "classes": ctx["classes"][:15], "modules": ctx["modules"][:20]}, indent=2)}

Write a comprehensive system overview (500-700 words) that:
- Describes the overall system architecture (layers, components)
- Explains how the major modules interact
- Covers the data flow through the system
- Mentions the deployment environment
- Describes the overall design philosophy

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "System overview not available.")

    async def _generate_existing_system(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the EXISTING SYSTEM sub-section (5.1) of a formal academic project report.

Project context:
{json.dumps({"project_name": ctx["project_name"], "github_url": ctx["github_url"], "tech_hints": ctx["tech_hints"], "analysis_summary": ctx["analysis_summary"]}, indent=2)}

Write about the Existing System (300-500 words) covering:
- What systems or manual processes existed before this project
- Drawbacks and limitations of the existing approach
- Why a new system was needed
- Any legacy tools or technologies that were in use

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "Existing system description not available.")

    async def _generate_proposed_system(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the PROPOSED SYSTEM sub-section (5.2) of a formal academic project report.

Project details:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "analysis_summary": ctx["analysis_summary"], "architecture_summary": ctx["architecture_summary"]}, indent=2)}

Write about the Proposed System (400-600 words) covering:
- Key features and advantages of the new system
- How it overcomes the limitations of the existing system
- New capabilities introduced
- Expected benefits (performance, usability, scalability)

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "Proposed system description not available.")

    async def _generate_literature_survey(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the LITERATURE SURVEY section of a formal academic project report.

Technology context (inferred from imports/modules):
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "imports": ctx["imports"][:30], "analysis_summary": ctx["analysis_summary"]}, indent=2)}

Write a Literature Survey (500-700 words) that:
- Reviews 4-6 related works, papers, or existing systems in the problem domain
- Compares their approaches and limitations
- Identifies the research gap this project fills
- Cites relevant technologies, frameworks, and methodologies mentioned or implied
- Concludes with a summary of what differentiates this project

Use formal academic English. Use numbered references like [1], [2], etc. Output plain text paragraphs."""
        return await self._call_llm(prompt, "Literature survey not available.")

    async def _generate_hardware_requirements(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the HARDWARE REQUIREMENTS sub-section (8.1) of a formal academic project report.

Project technology stack (from imports/modules):
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "imports": ctx["imports"][:20], "modules": ctx["modules"][:10]}, indent=2)}

List the minimum and recommended hardware requirements for:
- Development environment
- Deployment / production server
Include: Processor, RAM, Storage, Network, GPU (if applicable).
Format as a clear list. Output plain text only (no markdown)."""
        return await self._call_llm(prompt, "Hardware requirements not available.")

    async def _generate_software_requirements(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the SOFTWARE REQUIREMENTS sub-section (8.2) of a formal academic project report.

Detected dependencies and technologies:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "imports": ctx["imports"][:40], "modules": ctx["modules"][:15], "analysis_summary": ctx["analysis_summary"]}, indent=2)}

List all software requirements including:
- Operating System
- Runtime environments (Python version, Node.js, etc.)
- Frameworks and libraries (with versions if detectable)
- Database systems
- Development tools (IDE, version control)
- Third-party services / APIs

Format as a clear numbered or grouped list. Output plain text only."""
        return await self._call_llm(prompt, "Software requirements not available.")

    async def _generate_technology_description(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the TECHNOLOGY DESCRIPTION sub-section (9.1) of a formal academic project report.

Technologies detected in the project:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "imports": ctx["imports"][:40], "modules": ctx["modules"][:15], "architecture_summary": ctx["architecture_summary"]}, indent=2)}

Write a Technology Description (500-700 words) that:
- Describes each major technology/framework used (purpose, why chosen)
- Covers language(s), web framework, database, LLM/AI frameworks, testing tools
- Explains how the technologies integrate with each other
- Mentions any cloud services or external APIs

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "Technology description not available.")

    async def _generate_module_description(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the MODULE DESCRIPTION sub-section (9.2) of a formal academic project report.

Modules, classes, and functions detected:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "modules": ctx["modules"][:30], "classes": ctx["classes"][:20], "functions": ctx["functions"][:20]}, indent=2)}

Write a Module Description (500-700 words) covering each major module/component:
- Module name and file path
- Purpose and responsibility
- Key classes and functions within the module
- Inputs and outputs
- Dependencies on other modules

Use formal academic English. Output plain text paragraphs grouped by module."""
        return await self._call_llm(prompt, "Module description not available.")

    async def _generate_sdlc_methodology(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the SDLC METHODOLOGY section of a formal academic project report.

Project context:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "analysis_summary": ctx["analysis_summary"], "modules": ctx["modules"][:10]}, indent=2)}

Write an SDLC Methodology section (400-600 words) covering:
- Which SDLC model was used (Agile, Waterfall, Spiral, etc.) and why it was chosen
- Phases of development followed (Requirements, Design, Implementation, Testing, Deployment)
- How each phase was executed in this project
- Tools used for project management

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "SDLC methodology not available.")

    async def _generate_system_design(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the SYSTEM DESIGN section of a formal academic project report.

Architecture and structure:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "architecture_summary": ctx["architecture_summary"], "classes": ctx["classes"][:20], "modules": ctx["modules"][:25]}, indent=2)}

Write the System Design section (600-800 words) covering:
- High-level architecture diagram description (layers, tiers)
- Database design (ER diagram description, tables/collections)
- Class diagram overview (major classes and relationships)
- Sequence/flow diagrams description for key use cases
- API design and endpoint structure
- Data flow between components

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "System design not available.")

    async def _generate_coding(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the CODING section of a formal academic project report.

Code structure details:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "modules": ctx["modules"][:30], "classes": ctx["classes"][:15], "functions": ctx["functions"][:20], "analysis_summary": ctx["analysis_summary"]}, indent=2)}

Write the Coding section (500-700 words) covering:
- Programming languages and coding standards followed
- Key algorithms and data structures implemented
- Description of the most important source files and their role
- Code organisation and folder structure
- Any design patterns applied
- Error handling and logging approach

Use formal academic English. Output plain text paragraphs (include brief code references by module name, not actual code blocks)."""
        return await self._call_llm(prompt, "Coding section not available.")

    async def _generate_testing(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the TESTING section of a formal academic project report.

Project context:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "analysis_summary": ctx["analysis_summary"], "api_summary": ctx["api_summary"]}, indent=2)}

Write the Testing section (500-700 words) covering:
- Types of testing performed (unit, integration, system, acceptance)
- Testing tools and frameworks used
- Test case descriptions for key modules/endpoints (at least 5 test cases in table format described in plain text)
- Test results summary (pass/fail counts if inferable)
- Bug tracking and resolution approach

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "Testing section not available.")

    async def _generate_output_screens(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the OUTPUT SCREENS section of a formal academic project report.

API endpoints and system features:
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "modules": ctx["modules"][:10], "api_summary": ctx["api_summary"], "api_metadata": ctx["api_metadata"]}, indent=2)}

Write the Output Screens section (300-500 words) that:
- Describes the key user interfaces or API response outputs of the system
- Describes what the user/client would see for each major feature
- Mentions specific endpoints/screens and what they display
- Notes for each screen: purpose, key data shown, user interactions possible

Note: Since this is an API-based system, describe the JSON response structures and any CLI/web UI outputs.
Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "Output screens section not available.")

    async def _generate_conclusion(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the CONCLUSION section of a formal academic project report.

Project summary:
{json.dumps({"project_name": ctx["project_name"], "github_url": ctx["github_url"], "tech_hints": ctx["tech_hints"], "analysis_summary": ctx["analysis_summary"], "architecture_summary": ctx["architecture_summary"]}, indent=2)}

Write a Conclusion (300-500 words) that:
- Summarises what was built and the key achievements
- Reflects on whether the objectives were met
- Discusses limitations of the current implementation
- Suggests future enhancements and directions for further work
- Closes with the broader impact/significance of the project

Use formal academic English. Output plain text paragraphs."""
        return await self._call_llm(prompt, "Conclusion not available.")

    async def _generate_references(self, ctx: Dict[str, Any]) -> str:
        prompt = f"""You are writing the REFERENCES section of a formal academic project report.

Technologies and frameworks used (from imports):
{json.dumps({"project_name": ctx["project_name"], "tech_hints": ctx["tech_hints"], "imports": ctx["imports"][:40], "modules": ctx["modules"][:10]}, indent=2)}

Generate a References list (8-15 entries) in IEEE format covering:
- Official documentation for each major framework/library detected
- Academic papers or books on relevant topics (AI, software engineering, etc.)
- Relevant RFCs or standards (e.g. OpenAPI, REST)

Format each reference on a new line as:
[N] Author(s), "Title," Publisher/Journal, Year. URL if applicable.

Output plain text only."""
        return await self._call_llm(prompt, "References not available.")
